### ISSUE TITLE
Fragment contents render out of order when loaded later

### ISSUE THREAD

**Issue by srchulo** [y-nk/vue-fragment#12]
I'm not sure if this would be a vue-fragment issue or not, so feel free to close if it isn't. I have a table like this:

```
<table>
    <TrComponent/>
    <TrComponentUsingVueFragment/>
    <TrComponent/>
</table>
```

`TrComponentUsingVueFragment` loads using an API. When it loads, it is placed after the TrComponents beneath it. To solve for now, I did this in `TrComponentUsingVueFragment`:

```
<template>
    <div v-if="!loaded"></div>
    <Component v-for=""...>
</template>
```

And having that div 'hold the place' seems to work well.

**Comment by y-nk** [comment]
@srchulo thanks for the feedback. I probably should be a vue-fragment side effect. The core logic is to use a directive to move the children of your fragment to the level of the fragment placeholder (a dumb div) ; so if there's no placeholder, i guess it will not find a suitable place to add the children.

I will investigate on that with a small example to reproduce the issue and let you know the outcome. I'm glad you can find a hack which suits your case.

**Comment by y-nk** [comment]
@srchulo It feels to me your issue isn't related. I created a usecase on this fiddle : http://jsfiddle.net/j5ztxpLu/

Could you tell me if it reflects your problem ?

**Comment by srchulo** [comment]
So I think I wasn't clear enough above, in that this component:

` <TrComponentUsingVueFragment/>`

Contains a component using `v-for`, that initially is empty:

```
<template>
  <fragment>
    <div v-if="!loaded"></div>
    <TrRow v-for="item in items" v-bind:item="item" v-bind:key="item.key"/>
  </fragment>
</template>
```

I think this fiddle shows the problem:

https://jsfiddle.net/9osyaq76/3/


OHAYOU2 and GOZAIMASU2 both end up at the bottom, which is what I'm seeing in my component.

**Comment by srchulo** [comment]
Also, I should note above that in order for it to not work the `div` tag above needs to be gone.

**Comment by y-nk** [comment]
@srchulo I think it's related to the way children are added at the beginning. As the fragment is empty at the beginning, the method called to add the child after loading should be `appendChild`, but as the directive has already did its magic, it calls appendChild on the parent.

It should be easy to fix.

**Comment by srchulo** [comment]
Awesome! Thank you for the quick fix :D
