### ISSUE TITLE
Question about vue router ?

### ISSUE THREAD

**Issue by f3ltron** [y-nk/vue-fragment#13]
Hello i am not sure if i will something stupid but it seem's not working with vue router right ?

**Comment by y-nk** [comment]
I honestly didn't tested to put a fragment in Vue router directly, so, it could be not working. That said, i don't see why it would not work, since it's a post-render (directive) oriented solution which doesn't mess up with the vdom.

If you have a non working example, please let me know and we can work it out.

**Comment by f3ltron** [comment]
``` 
a simple vue router like 

<fragment>
<button @click="$router.push('/')" >home</button>
another button here to another route
<router-view></router-view>
</fragment>
```

do two routes on it

when you call the next route it will throw an error can use insert before because of non parent

**Comment by f3ltron** [comment]
damn it is working pretty well for you hum... Ok i will try it so thx !

**Comment by y-nk** [comment]
@f3ltron no worries. either it could be fized because of the new version pushed, either your bug is not directly related but i'd like to know about it anyway. let me know how it goes.

**Comment by adi518** [comment]
I also tested it and it works. No issue afaik. :)

**Comment by alvaro-canepa** [comment]
I have the latest v1.2.0, and sometimes get error `Error in directive fragment inserted hook: "TypeError: Cannot read property 'insertBefore' of null"`. I think this happen when do `this.$router.push('/path')`.

**Comment by y-nk** [comment]
@alvaro-canepa thanks for your feedback.

The simpliest example i could come up didn't raise any error, so it's quite hard to provide a fix.

As you seem to encounter problems, would you mind sending a fiddle with a reproduction of the bug ? i'll investigate from there, but if i can't reproduce the bug, I can't fix it for you...

**Comment by alvaro-canepa** [comment]
@y-nk Thanks for your fast response ;)
I will try to reproduce de error in fiddle.

**Comment by OmgImAlexis** [comment]
I believe this is related.

```
index.js?1ef8:2178 [Vue warn]: Error in directive fragment inserted hook: "TypeError: Cannot read property 'insertBefore' of null"

found in

---> <Fragment>
       <HelpLink> at components/helpers/help-link.vue
         <DeviceList> at components/device-list/device-list.vue
           <Home> at components/home/index.vue
             <DetectNetwork> at components/helpers/detect-network.vue
               <App> at components/app.vue
                 <Root>
index.js?1ef8:2178 TypeError: Cannot read property 'insertBefore' of null
    at inserted (vue-fragment.esm.js?3f08:1)
    at callHook$1 (vue.runtime.esm.js?2b0e:6289)
    at callInsert (vue.runtime.esm.js?2b0e:6228)
    at wrappedHook (vue.runtime.esm.js?2b0e:2076)
    at Object.invoker [as insert] (vue.runtime.esm.js?2b0e:2019)
    at invokeInsertHook (vue.runtime.esm.js?2b0e:5956)
    at VueComponent.patch [as __patch__] (vue.runtime.esm.js?2b0e:6175)
    at VueComponent.Vue._update (vue.runtime.esm.js?2b0e:2666)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:2784)
    at Watcher.get (vue.runtime.esm.js?2b0e:3138)
    at Watcher.run (vue.runtime.esm.js?2b0e:3215)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:2977)
    at Array.eval (vue.runtime.esm.js?2b0e:1833)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1754)
```

**Comment by y-nk** [comment]
@OmgImAlexis could you share some of your code so i could isolate the problem ? it seems many people experience that, so i wish to fix it but cannot reproduce.

**Comment by OmgImAlexis** [comment]
Sure, what part would help?

**Comment by y-nk** [comment]
@OmgImAlexis the part which uses the component, until it leads to the error :)

**Comment by OmgImAlexis** [comment]
I believe this is the component causing the issue. I know it's a tad unconventional but it does work after going to a page(router push) and then back. In saying that, I do get that error on load and the event handler isn't added to the correct element until after coming BACK to the first page.

I hope I'm just misusing this somehow.

```
<template>
	<component v-if="tag" :is="tag" ref="component">
		<component :is="component">
			<slot></slot>
		</component>
	</component>
	<component v-else :is="component">
		<slot></slot>
	</component>
</template>

<script>
/**
 * Open help box on click
 */
export default {
	name: 'help-link',
	data() {
		return {
			show: false,
			el: null
		};
	},
	props: {
		name: {
			type: String,
			default: '*'
		},
		exclude: {
			type: Boolean,
			default: true
		},
		tag: {
			type: String
		}
	},
	methods: {
		handler() {
			this.show = !this.show;
			this.$bus.emit(`help:${this.name}:${this.show ? 'show' : 'hide'}`);
		}
	},
	computed: {
		component() {
			const { exclude } = this
			const excluded = [
				'table',
				'thead',
				'tbody',
				'td',
				'tr'
			];

			if (this.exclude && excluded.includes(this.$slots.default[0].tag)) {
				return 'fragment';
			}

			return 'a';
		}
	},
	created() {
		// Set key to name
		this.$vnode.key = this.name;
	},
	mounted() {
		if (this.component === 'fragment') {
			return;
		}

		// Save for later
		this.el = this.$el;

		// Set cursor
		this.el.style.cursor = 'help';

		// Add emitter to click event
		this.el.addEventListener('click', this.handler);
	},
	beforeDestroy() {
		if (this.component === 'fragment') {
			return;
		}
		
		this.el.removeEventListener('click', this.handler);
	}
}
</script>
```

**Comment by y-nk** [comment]
@f3ltron @OmgImAlexis I think i made a successful reproduction case, so i will start on fixing it.

**Comment by alvaro-canepa** [comment]
@y-nk I'm trying to reproduce the error from https://codesandbox.io/s/74rv1qr85q but codesandbox doesn't compile correctly the components. But maybe you can see, in my case, how I use `fragment`.
Thanks.

**Comment by y-nk** [comment]
@alvaro-canepa I found the same. http://jsfiddle.net/y_nk/54am0ouL/

**Comment by f3ltron** [comment]
i am actually streaming twitch.tv/f3ltron and i tipically have the error

**Comment by adi518** [comment]
I looked at it and it seems the issue stems from the dynamic rendering of nested `fragment` components. The Fragment directive assumes the parent is always a real element and clings onto that. It seems we have to lookup a real parent recursively, which theoretically, can reach up to the root element of the app.

**Comment by f3ltron** [comment]
i tried with a parent root not with fragment but get the same issue

**Comment by adi518** [comment]
@f3ltron Can you post an example?

**Comment by f3ltron** [comment]
as i mentionned something with a parent without fragment

https://codesandbox.io/s/v8oww796y5

**Comment by y-nk** [comment]
@f3ltron @adi518 i've been working on a stronger implementation which support nesting and fixes this bug. i'm fixing a final bug about recursive removal and it'll be good for testing. would you mind trying it before i publish it ?

**Comment by y-nk** [comment]
@adi518 i'm gonna see about having router-view inside a fragment. thanks for your time and testing. I agree we'd need tests. It's probably gonna be the next step after stabilizing the package.
on a side note, the `name` prop is only here as a decoration. it becomes handy when you want to write css selectors to target fragment root elements which are demonstrated in the demo with `*[fragment=nameprop]`

**Comment by y-nk** [comment]
@adi518 i updated the same codesandbox with fixes. it looks now working with vue-router, both inside and outside of `router-view` component.

- https://codesandbox.io/s/pp16k99yz0

**Comment by OmgImAlexis** [comment]
@y-nk in the example you linked above I still managed to reproduce the error. I randomly removed and re-added children. 

![screen shot 2018-11-21 at 4 47 22 pm](https://user-images.githubusercontent.com/6525926/48822487-2757f100-edad-11e8-9e91-9e86a74e1ad2.png)

**Comment by y-nk** [comment]
@OmgImAlexis thanks for your feedback. i could reproduce this bug. i didn't think about this case... i'll fix it :)

**Comment by y-nk** [comment]
@adi518 @f3ltron @OmgImAlexis would you mind trying to test this one real quick : https://codesandbox.io/s/rm2456v4lm ?

**Comment by f3ltron** [comment]
i will try

**Comment by f3ltron** [comment]
for me it's working well. Is there any performance impact of using fragment ? Should we consider to use it in production ?

**Comment by f3ltron** [comment]
working with my stylguide and uni test in my vue-scaler project feel free to check https://github.com/f3ltron/vue-scaler.git and maybe help 👍 If it's ok i will use as much as possible your vue fragment it's totally in adequation with my project goal

**Comment by y-nk** [comment]
@f3ltron thanks for the review. it's published as @1.5.0 :)

I don't see a lot of overhead, although it's worth noticing it does mutate the dom after render. for such reason, i'm questioning Vue's capacity to diff the dom correctly.

**Comment by OmgImAlexis** [comment]
@y-nk I've tried the new version and although it's fixed most of the errors I still get the `Cannot read property 'insertBefore' of null` in some places. Shall I open a new issue?

**Comment by y-nk** [comment]
@OmgImAlexis please do, along with a minimal reproductible example. I'll investigate about it.
