### ISSUE TITLE
v-fragment not working?

### ISSUE THREAD

**Issue by milewski** [y-nk/vue-fragment#14]
Hi after migrating from `vue-fragments` to `vue-fragment` the `v-fragment` directive no longer works..

```
vendor.c6089.js:41290 [Vue warn]: Unknown custom element: <v-fragment> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in
```

**Comment by adi518** [comment]
See #8. The component should be imported as `Fragment` and used in template like so: `<fragment></fragment>`.
