### ISSUE TITLE
fragment is not working with v-if

### ISSUE THREAD

**Issue by nmanikiran** [y-nk/vue-fragment#19]
the **fragment** is not working with v-if

I have a use case:
 
on click a elements/component I need to show overlay both are siblings under fragments the overlay component has v-if it's not showing.
in **vue-tools** it's showing it but in the DOM (it's not rendering).

So I created some mock example in [fiddle](http://jsfiddle.net/cwfn8Lrx/)

**Comment by y-nk** [comment]
I'm not sure how i can help you on that since you're not using `vue-fragment` but a domfragment instead.
