### ISSUE TITLE
id not being passed to fragment parent

### ISSUE THREAD

**Issue by OmgImAlexis** [y-nk/vue-fragment#20]
After updating from the npm version to the latest Github copy I've come across this issue. It seems as though the id isn't being copied across.

```vue
<template>
	<fragment>
		<div id="header" class="image">
		</div>
	</fragment>
</template>
```

-----
> Before:
![screen shot 2018-12-22 at 6 15 53 pm](https://user-images.githubusercontent.com/6525926/50371997-d179a180-0615-11e9-96be-e965c0579df0.png)

-----
> After:
![screen shot 2018-12-22 at 6 16 02 pm](https://user-images.githubusercontent.com/6525926/50371996-d179a180-0615-11e9-9fe8-60b5b4c499a9.png)

**Comment by y-nk** [comment]
From your screenshot, i can see that your goal is to replace `<div id="header">` by `<fragment id="header">`, which is a different goal than the snippet you posted above.

This fragment implementation is an _abstract_ piece which _unwraps_ all the children in the parent, and has no root node. Therefore, attaching dom attributes **is useless**. The `<div fragment="">` is a temporary root node implementation which is detached after mounting, and should not be here (or probably, in SSR). You should not relay on it for any selector, or feature related to the fragment's content.

**Comment by OmgImAlexis** [comment]
@y-nk not sure which of us seems to be confused here but neither the answer from here or the one you gave on https://github.com/y-nk/vue-fragment/issues/21 makes sense?

Both of us had our code working fine on the old version of this package. Would you mind showing an example of how to fix either of our code pieces so we know how we're meant to be using it?

**Comment by OmgImAlexis** [comment]
Those two screenshots are from before and after updating to the "stronger implementation" commit.

The code from the screenshots is also the same code from the snippet, I simply removed the other sections of code inside it. Not sure what you had meant by what you said.. 🤔

**Comment by string-areeb** [comment]
I think the package is broken and @y-nk doesn't realize this.

**Comment by OmgImAlexis** [comment]
@string-areeb I think it's `v1.2.2`.

**Comment by string-areeb** [comment]
Thanks
