### ISSUE TITLE
`data-` is not passing to fragment

### ISSUE THREAD

**Issue by Javid-Izadfar** [y-nk/vue-fragment#21]
I'm using version 1.5.0 and `data-` properties are not passing to fragments.

example:
```
<fragment>
      <div data-foo="bar">...</div>
</fragment>
```
expected result:
```
<div fragment="123124124" data-foo="bar">...</div>
```
given result:
```
<div fragment="123124124">...</div>
```

**Comment by OmgImAlexis** [comment]
Sounds like these are both related to this line https://github.com/y-nk/vue-fragment/blob/master/src/component.js#L98

**Comment by OmgImAlexis** [comment]
PING: @y-nk

**Comment by OmgImAlexis** [comment]
PING: @y-nk

**Comment by y-nk** [comment]
@Javid-Izadfar There's a misconception of the expected result.

Given : 

```
<fragment>
      <div data-foo="bar">...</div>
</fragment>
```

The actual result is (should be, at least) : 

```
<!-- fragment#123124124#head -->
<div data-foo="bar">...</div>
<!-- fragment#123124124#tail -->
```

**without** a parent div.

The `<div fragment="123124124">` is a temporary placeholder used to gather children and locate point of insertion in the parent node, and is removed after. Therefore, it's useless to try to pass down dom attributes.
