### ISSUE TITLE
No declaration file for TypeScript support

### ISSUE THREAD

**Issue by douglasg14b** [y-nk/vue-fragment#28]
As the title says, TypeScript throws an error since there is no declaration file for the lib when implicit any is off.

**Comment by y-nk** [comment]
I'm not a user of TS, nor a big fan of it, but i understand people would need this.
Please feel free to PR it.

**Comment by ChuckBorris33** [comment]
For anyone waiting for this to be released. You can add declarations to your project.
Add file e.g. `shims.vue-fragment.d.ts` with content: 
```typescript
declare module 'vue-fragment' {
  import Vue, { AsyncComponent, ComponentOptions, PluginObject } from 'vue'

  type Component = ComponentOptions<Vue> | typeof Vue | AsyncComponent

  export const Fragment: Component
  export const Plugin: PluginObject<undefined>

  namespace VueFragment {
    export const Fragment: Component
    export const Plugin: PluginObject<undefined>
  }
  export default VueFragment
}
```
