### ISSUE TITLE
Publish update to npmjs

### ISSUE THREAD

**Issue by Spaggel** [y-nk/vue-fragment#29]
Hi, 
I'm using this plugin and really like it but had a problem with missing attributes. The problem is fixed by PR #25 which you merged yesterday.

Could you bump the version and push to npmjs so I can use the fixed version instead of building the plugin myself?

Thanks in advance.

**Comment by lherman-cs** [comment]
+1 on this

**Comment by lherman-cs** [comment]
@Spaggel alternatively, we can currently install the package by `npm i git+https://github.com/y-nk/vue-fragment.git && cd node_modules/vue-fragment && npm i`. Not the best, but it works!

**Comment by Spaggel** [comment]
@lherman-cs thanks for your reply. I'm using a _postinstall_ script to automatically build the JS file as shown below: 
`"scripts": {
        "postinstall": "cd node_modules/vue-fragment && npm install"
    },`

I hope this helps some people until it gets updated on npmjs.

**Comment by y-nk** [comment]
`v1.5.1`
