### ISSUE TITLE
Rename component and export to "Fragment"

### ISSUE THREAD

**Issue by adi518** [y-nk/vue-fragment#8]
It just hit me that in order to secure a seamless upgrade once Vue adds a builtin component, the placeholder component must be named `fragment` instead of `v-fragment`. However, changing the name isn't enough as it does not affect its import or its namespace in template composition. Therefore, its export must be named to avoid inconsistent imports. With that said, forcing a named export may suggest a new major version. If you want to be really strict, assign it as patch, code will break, but it will straighten things before the consumer base of this package becomes significant.

Example (global install, which is the recommended way, as all Vue built-ins are global):
```js
// main.js
import { Plugin as Fragment } from 'vue-fragments'

Vue.use(Fragment.component)
```

SFC Example (although not so realistic in Vue context):
```js
// my-component.js
import { Fragment } from 'vue-fragments'

export default {
  components: Fragment
}
```

Once Vue adds a builtin, all the consumer has to do, is remove this snippet from their code.

P.S.,
I don't see the value of the directive. The directive result is an implementation detail, so using it seems more like an incomplete solution:

```vue
<div v-fragment>
 <span></span>
 <span></span>
</div>
```

The consumer doesn't care whether it's a `div` or something else, so we can decide that for them by abstracting it as a component, which uses a `div` (which is what the current implementation does). This means you should exclude the directive from the package, unless I'm missing some kind of use-case. Also, this will align with how it is done in React:

```js
import { Component, Fragment } from 'react'

export class Foo extends Component {
  render() {
    return (<Fragment></Fragment>)
  }
}
```

P.S. 2,
As a general rule of thumb, I'd decouple plugin installation, so a consumer can cherry-install, like so:

```js
// index.js
export default {
  Plugin: {
    component: {
      install(Vue) {
        Vue.component('my-component', myComponent)
      }
    },
    directive: {
      install(Vue) {
        Vue.directive('my-directive', directive)
      }
    }
  }
}

// Usage (main.js)
import { Plugin as Fragment } from 'vue-fragments'

Vue.use(Fragment.component)
```

**Comment by tesla3327** [comment]
I definitely agree with this, especially with the directive part. 

In fact, since all of the logic is DOM manipulation, you could extract all of it to helper functions. Then use those helper functions in the component/directive. It would help to keep this library extremely light weight. The value this lib brings are those few dozen lines of code.

You could even just export those helper functions, although I think wrapping it up in a nice `<Fragment />` component is needed as well.

**Comment by adi518** [comment]
Today, it was revealed that next iteration of Vue (major version 3) will include Fragments and Portals as builtins: https://medium.com/the-vue-point/plans-for-the-next-iteration-of-vue-js-777ffea6fabf.

**Comment by y-nk** [comment]
@tesla3327 i agree with this as well. I'll try to find some time during the next weeks to move in that direction.

**Comment by y-nk** [comment]
@adi518 @tesla3327 i've been rewriting according to your comments, and the only reason why i wasn't using functional components was my first idea of using a directive ; as you said, directive is mainly a detail, so maybe it could have been removed ; so i tried what i commented before, and it looks also working.

http://jsfiddle.net/pL903avr/

what do you think ?

**Comment by y-nk** [comment]
@adi518 @tesla3327 thanks for your suggestions. these have been added, along with moving to `vue-fragment` (without S).
